### ISSUE TITLE
Cottage fails to compile from AUR

### ISSUE THREAD

**Issue by ThurnisH41ey** [HarveyHunt/cottage#8]
`makepkg -si`
returns [this](https://gist.github.com/f4731a1973a8ba3026b8) error output. Using latest build (pulled from AUR using cower).

**Comment by HarveyHunt** [comment]
I just spoke to the AUR package maintainer and he will modify the PKGBUILD to fix this. :+1:

**Comment by HarveyHunt** [comment]
All fixed, thanks @aladw :-)

**Comment by ThurnisH41ey** [comment]
`makepkg -si`
is now failing [here](https://gist.github.com/3b2b4b4b6aa946c1b356)

**Comment by HarveyHunt** [comment]
Ahhhh, I modified the Makefile in f4862bf3ed4d1819d22e14da3facbdd6db159248 and forgot to tell @aladw about the change in the output directory.

Cottage now outputs a binary in the pwd called ```cottage``` - it's no longer in a directory.

**Comment by AladW** [comment]
Updated, should work now:

https://aur.archlinux.org/cgit/aur.git/commit/?h=cottage-git&id=717eb9543065f7e45d16be7212106a1f1ddcaabe

**Comment by HarveyHunt** [comment]
Thanks @AladW :-)

**Comment by ThurnisH41ey** [comment]
Thanks guys! Appreciate the timely responses, can't wait to try out howm!
